[2024-09-19 05:24:56,333][flwr][INFO] - Starting Flower simulation, config: num_rounds=100, no round_timeout
[2024-09-19 05:24:59,538][flwr][INFO] - Flower VCE: Ray initialized with resources: {'node:115.145.172.224': 1.0, 'object_store_memory': 67958715187.0, 'node:__internal_head__': 1.0, 'CPU': 256.0, 'memory': 148570335437.0, 'accelerator_type:G': 1.0, 'GPU': 1.0}
[2024-09-19 05:24:59,539][flwr][INFO] - Optimize your simulation with Flower VCE: https://flower.ai/docs/framework/how-to-run-simulations.html
[2024-09-19 05:24:59,539][flwr][INFO] - Flower VCE: Resources for each Virtual Client: {'num_cpus': 16, 'num_gpus': 0.5}
[2024-09-19 05:24:59,552][flwr][INFO] - Flower VCE: Creating VirtualClientEngineActorPool with 2 actors
[2024-09-19 05:24:59,552][flwr][INFO] - [INIT]
[2024-09-19 05:24:59,553][flwr][INFO] - Requesting initial parameters from one random client
[2024-09-19 05:25:06,198][flwr][INFO] - Received initial parameters from one random client
[2024-09-19 05:25:06,198][flwr][INFO] - Evaluating initial global parameters
[2024-09-19 05:25:16,551][flwr][INFO] - initial parameters (loss, other metrics): 236.95961356163025, {'accuracy': 0.07483192049108447}
[2024-09-19 05:25:16,552][flwr][INFO] - 
[2024-09-19 05:25:16,552][flwr][INFO] - [ROUND 1]
[2024-09-19 05:25:16,552][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 05:25:35,006][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 05:25:36,517][flwr][WARNING] - No fit_metrics_aggregation_fn provided
[2024-09-19 05:25:46,209][flwr][INFO] - fit progress: (1, 314.8323600292206, {'accuracy': 0.1824028061970184}, 29.656978441867977)
[2024-09-19 05:25:46,209][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 05:25:49,450][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 05:25:49,450][flwr][INFO] - 
[2024-09-19 05:25:49,450][flwr][INFO] - [ROUND 2]
[2024-09-19 05:25:49,450][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 05:26:03,137][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 05:26:14,476][flwr][INFO] - fit progress: (2, 275.57846319675446, {'accuracy': 0.1824028061970184}, 57.92439053580165)
[2024-09-19 05:26:14,477][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 05:26:17,561][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 05:26:17,561][flwr][INFO] - 
[2024-09-19 05:26:17,561][flwr][INFO] - [ROUND 3]
[2024-09-19 05:26:17,561][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 05:26:30,983][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 05:26:42,595][flwr][INFO] - fit progress: (3, 232.24409687519073, {'accuracy': 0.0710318620286466}, 86.04286927403882)
[2024-09-19 05:26:42,595][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 05:26:46,110][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 05:26:46,111][flwr][INFO] - 
[2024-09-19 05:26:46,111][flwr][INFO] - [ROUND 4]
[2024-09-19 05:26:46,111][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 05:27:02,295][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 05:27:12,987][flwr][INFO] - fit progress: (4, 236.0022075176239, {'accuracy': 0.09090909090909091}, 116.43489624606445)
[2024-09-19 05:27:12,987][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 05:27:16,054][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 05:27:16,055][flwr][INFO] - 
[2024-09-19 05:27:16,055][flwr][INFO] - [ROUND 5]
[2024-09-19 05:27:16,055][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 05:27:36,071][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 05:27:47,137][flwr][INFO] - fit progress: (5, 223.45547807216644, {'accuracy': 0.16924875767319497}, 150.5851326189004)
[2024-09-19 05:27:47,137][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 05:27:50,339][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 05:27:50,339][flwr][INFO] - 
[2024-09-19 05:27:50,340][flwr][INFO] - [ROUND 6]
[2024-09-19 05:27:50,340][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 05:28:06,448][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 05:28:17,770][flwr][INFO] - fit progress: (6, 275.6538553237915, {'accuracy': 0.1373867290266004}, 181.21836439985782)
[2024-09-19 05:28:17,771][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 05:28:21,241][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 05:28:21,241][flwr][INFO] - 
[2024-09-19 05:28:21,241][flwr][INFO] - [ROUND 7]
[2024-09-19 05:28:21,241][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 05:28:39,824][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 05:28:51,720][flwr][INFO] - fit progress: (7, 244.8714678287506, {'accuracy': 0.19467991815258695}, 215.16844577668235)
[2024-09-19 05:28:51,721][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 05:28:55,261][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 05:28:55,261][flwr][INFO] - 
[2024-09-19 05:28:55,261][flwr][INFO] - [ROUND 8]
[2024-09-19 05:28:55,261][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 05:29:06,304][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=2755588, ip=115.145.172.224, actor_id=06771556b6217d876bf7275301000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f14f8275960>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_vgg16/fedavg_vgg16/client.py", line 91, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=2755588, ip=115.145.172.224, actor_id=06771556b6217d876bf7275301000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f14f8275960>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-09-19 05:29:06,304][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=2755588, ip=115.145.172.224, actor_id=06771556b6217d876bf7275301000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f14f8275960>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_vgg16/fedavg_vgg16/client.py", line 91, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=2755588, ip=115.145.172.224, actor_id=06771556b6217d876bf7275301000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f14f8275960>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-09-19 05:29:06,305][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-09-19 05:29:18,070][flwr][INFO] - fit progress: (8, 358.55996656417847, {'accuracy': 0.1824028061970184}, 241.5186123298481)
[2024-09-19 05:29:18,071][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 05:29:21,235][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 05:29:21,236][flwr][INFO] - 
[2024-09-19 05:29:21,236][flwr][INFO] - [ROUND 9]
[2024-09-19 05:29:21,236][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 05:29:23,723][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=2755587, ip=115.145.172.224, actor_id=74c709537b1b0ff8d220f38401000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f3a60179930>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_vgg16/fedavg_vgg16/client.py", line 91, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=2755587, ip=115.145.172.224, actor_id=74c709537b1b0ff8d220f38401000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f3a60179930>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-09-19 05:29:23,723][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=2755587, ip=115.145.172.224, actor_id=74c709537b1b0ff8d220f38401000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f3a60179930>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_vgg16/fedavg_vgg16/client.py", line 91, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=2755587, ip=115.145.172.224, actor_id=74c709537b1b0ff8d220f38401000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f3a60179930>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-09-19 05:29:32,530][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-09-19 05:29:43,472][flwr][INFO] - fit progress: (9, 221.96499860286713, {'accuracy': 0.1373867290266004}, 266.92050790181383)
[2024-09-19 05:29:43,473][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 05:29:46,727][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 05:29:46,728][flwr][INFO] - 
[2024-09-19 05:29:46,728][flwr][INFO] - [ROUND 10]
[2024-09-19 05:29:46,728][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 05:30:06,020][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 05:30:17,001][flwr][INFO] - fit progress: (10, 256.1852707862854, {'accuracy': 0.16924875767319497}, 300.44942556973547)
[2024-09-19 05:30:17,002][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 05:30:18,800][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=2755587, ip=115.145.172.224, actor_id=74c709537b1b0ff8d220f38401000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f3a60179930>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_vgg16/fedavg_vgg16/client.py", line 91, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=2755587, ip=115.145.172.224, actor_id=74c709537b1b0ff8d220f38401000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f3a60179930>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-09-19 05:30:18,800][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=2755587, ip=115.145.172.224, actor_id=74c709537b1b0ff8d220f38401000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f3a60179930>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_vgg16/fedavg_vgg16/client.py", line 91, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=2755587, ip=115.145.172.224, actor_id=74c709537b1b0ff8d220f38401000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f3a60179930>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-09-19 05:30:20,356][flwr][INFO] - aggregate_evaluate: received 1 results and 1 failures
[2024-09-19 05:30:20,356][flwr][INFO] - 
[2024-09-19 05:30:20,356][flwr][INFO] - [ROUND 11]
[2024-09-19 05:30:20,357][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 05:30:40,941][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 05:30:51,617][flwr][INFO] - fit progress: (11, 241.1495063304901, {'accuracy': 0.16924875767319497}, 335.0655009690672)
[2024-09-19 05:30:51,618][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 05:30:55,198][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 05:30:55,198][flwr][INFO] - 
[2024-09-19 05:30:55,198][flwr][INFO] - [ROUND 12]
[2024-09-19 05:30:55,198][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 05:31:12,822][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 05:31:23,848][flwr][INFO] - fit progress: (12, 243.75460958480835, {'accuracy': 0.1824028061970184}, 367.2966230097227)
[2024-09-19 05:31:23,849][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 05:31:27,649][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 05:31:27,649][flwr][INFO] - 
[2024-09-19 05:31:27,649][flwr][INFO] - [ROUND 13]
[2024-09-19 05:31:27,650][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 05:31:46,269][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 05:31:58,741][flwr][INFO] - fit progress: (13, 319.1035921573639, {'accuracy': 0.19467991815258695}, 402.18898868607357)
[2024-09-19 05:31:58,741][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 05:32:02,134][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 05:32:02,134][flwr][INFO] - 
[2024-09-19 05:32:02,134][flwr][INFO] - [ROUND 14]
[2024-09-19 05:32:02,134][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 05:32:14,213][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=2755587, ip=115.145.172.224, actor_id=74c709537b1b0ff8d220f38401000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f3a60179930>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_vgg16/fedavg_vgg16/client.py", line 91, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=2755587, ip=115.145.172.224, actor_id=74c709537b1b0ff8d220f38401000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f3a60179930>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-09-19 05:32:14,213][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=2755587, ip=115.145.172.224, actor_id=74c709537b1b0ff8d220f38401000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f3a60179930>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_vgg16/fedavg_vgg16/client.py", line 91, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=2755587, ip=115.145.172.224, actor_id=74c709537b1b0ff8d220f38401000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f3a60179930>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-09-19 05:32:16,693][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-09-19 05:32:27,473][flwr][INFO] - fit progress: (14, 370.9240219593048, {'accuracy': 0.19731072785735165}, 430.92109067877755)
[2024-09-19 05:32:27,473][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 05:32:31,310][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 05:32:31,310][flwr][INFO] - 
[2024-09-19 05:32:31,310][flwr][INFO] - [ROUND 15]
[2024-09-19 05:32:31,311][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 05:32:49,362][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 05:33:00,191][flwr][INFO] - fit progress: (15, 252.99449932575226, {'accuracy': 0.29494299912306343}, 463.63894345983863)
[2024-09-19 05:33:00,191][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 05:33:03,398][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 05:33:03,399][flwr][INFO] - 
[2024-09-19 05:33:03,399][flwr][INFO] - [ROUND 16]
[2024-09-19 05:33:03,399][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 05:33:16,537][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=2755588, ip=115.145.172.224, actor_id=06771556b6217d876bf7275301000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f14f8275960>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_vgg16/fedavg_vgg16/client.py", line 91, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=2755588, ip=115.145.172.224, actor_id=06771556b6217d876bf7275301000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f14f8275960>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-09-19 05:33:16,538][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=2755588, ip=115.145.172.224, actor_id=06771556b6217d876bf7275301000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f14f8275960>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_vgg16/fedavg_vgg16/client.py", line 91, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=2755588, ip=115.145.172.224, actor_id=06771556b6217d876bf7275301000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f14f8275960>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-09-19 05:33:16,538][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-09-19 05:33:27,100][flwr][INFO] - fit progress: (16, 229.98141658306122, {'accuracy': 0.10757088570593394}, 490.54797940375283)
[2024-09-19 05:33:27,100][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 05:33:30,689][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 05:33:30,690][flwr][INFO] - 
[2024-09-19 05:33:30,690][flwr][INFO] - [ROUND 17]
[2024-09-19 05:33:30,690][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 05:33:49,538][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 05:33:59,693][flwr][INFO] - fit progress: (17, 207.78885877132416, {'accuracy': 0.21631102016954107}, 523.1410871758126)
[2024-09-19 05:33:59,693][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 05:34:02,733][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 05:34:02,733][flwr][INFO] - 
[2024-09-19 05:34:02,734][flwr][INFO] - [ROUND 18]
[2024-09-19 05:34:02,734][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 05:34:21,031][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 05:34:31,188][flwr][INFO] - fit progress: (18, 194.9832283258438, {'accuracy': 0.31511254019292606}, 554.6364375497214)
[2024-09-19 05:34:31,189][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 05:34:34,637][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 05:34:34,637][flwr][INFO] - 
[2024-09-19 05:34:34,637][flwr][INFO] - [ROUND 19]
[2024-09-19 05:34:34,637][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 05:34:52,211][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 05:35:03,264][flwr][INFO] - fit progress: (19, 198.96304595470428, {'accuracy': 0.26132709733995907}, 586.7123706359416)
[2024-09-19 05:35:03,264][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 05:35:07,147][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 05:35:07,148][flwr][INFO] - 
[2024-09-19 05:35:07,148][flwr][INFO] - [ROUND 20]
[2024-09-19 05:35:07,148][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 05:35:26,675][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 05:35:37,624][flwr][INFO] - fit progress: (20, 349.6879804134369, {'accuracy': 0.4016369482607425}, 621.0721668438055)
[2024-09-19 05:35:37,624][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 05:35:40,971][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 05:35:40,971][flwr][INFO] - 
[2024-09-19 05:35:40,971][flwr][INFO] - [ROUND 21]
[2024-09-19 05:35:40,971][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 05:35:55,911][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 05:36:06,177][flwr][INFO] - fit progress: (21, 211.71223163604736, {'accuracy': 0.21280327389652148}, 649.6250951550901)
[2024-09-19 05:36:06,177][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 05:36:09,803][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 05:36:09,803][flwr][INFO] - 
[2024-09-19 05:36:09,803][flwr][INFO] - [ROUND 22]
[2024-09-19 05:36:09,803][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 05:36:28,163][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 05:36:38,352][flwr][INFO] - fit progress: (22, 197.83693420886993, {'accuracy': 0.31920491084478225}, 681.8006594209)
[2024-09-19 05:36:38,353][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 05:36:42,041][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 05:36:42,041][flwr][INFO] - 
[2024-09-19 05:36:42,041][flwr][INFO] - [ROUND 23]
[2024-09-19 05:36:42,041][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 05:36:59,949][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 05:37:10,038][flwr][INFO] - fit progress: (23, 220.7082303762436, {'accuracy': 0.3045893013738673}, 713.4866655990481)
[2024-09-19 05:37:10,039][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 05:37:13,799][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 05:37:13,800][flwr][INFO] - 
[2024-09-19 05:37:13,800][flwr][INFO] - [ROUND 24]
[2024-09-19 05:37:13,800][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 05:37:36,000][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 05:37:46,452][flwr][INFO] - fit progress: (24, 256.0654927492142, {'accuracy': 0.3051739257527039}, 749.8997894036584)
[2024-09-19 05:37:46,452][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 05:37:49,750][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 05:37:49,751][flwr][INFO] - 
[2024-09-19 05:37:49,751][flwr][INFO] - [ROUND 25]
[2024-09-19 05:37:49,751][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 05:38:05,316][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 05:38:15,797][flwr][INFO] - fit progress: (25, 199.01076793670654, {'accuracy': 0.3291435252850044}, 779.2450763578527)
[2024-09-19 05:38:15,797][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 05:38:19,448][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 05:38:19,448][flwr][INFO] - 
[2024-09-19 05:38:19,448][flwr][INFO] - [ROUND 26]
[2024-09-19 05:38:19,448][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 05:38:37,684][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 05:38:48,890][flwr][INFO] - fit progress: (26, 203.5955001115799, {'accuracy': 0.20140309850920785}, 812.3379711657763)
[2024-09-19 05:38:48,890][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 05:38:52,135][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 05:38:52,135][flwr][INFO] - 
[2024-09-19 05:38:52,135][flwr][INFO] - [ROUND 27]
[2024-09-19 05:38:52,135][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 05:39:08,268][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 05:39:19,502][flwr][INFO] - fit progress: (27, 239.97119915485382, {'accuracy': 0.2572347266881029}, 842.9504086249508)
[2024-09-19 05:39:19,503][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 05:39:22,933][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 05:39:22,933][flwr][INFO] - 
[2024-09-19 05:39:22,933][flwr][INFO] - [ROUND 28]
[2024-09-19 05:39:22,933][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 05:39:36,226][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 05:39:47,319][flwr][INFO] - fit progress: (28, 177.7108371257782, {'accuracy': 0.35603624671148787}, 870.7675753738731)
[2024-09-19 05:39:47,320][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 05:39:50,809][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 05:39:50,809][flwr][INFO] - 
[2024-09-19 05:39:50,809][flwr][INFO] - [ROUND 29]
[2024-09-19 05:39:50,809][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 05:40:06,496][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 05:40:18,096][flwr][INFO] - fit progress: (29, 221.1934574842453, {'accuracy': 0.28734288219818765}, 901.5440543200821)
[2024-09-19 05:40:18,096][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 05:40:21,288][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 05:40:21,288][flwr][INFO] - 
[2024-09-19 05:40:21,289][flwr][INFO] - [ROUND 30]
[2024-09-19 05:40:21,289][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 05:40:35,902][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 05:40:46,273][flwr][INFO] - fit progress: (30, 266.36865425109863, {'accuracy': 0.23531131248173048}, 929.7208400098607)
[2024-09-19 05:40:46,273][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 05:40:49,539][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 05:40:49,539][flwr][INFO] - 
[2024-09-19 05:40:49,539][flwr][INFO] - [ROUND 31]
[2024-09-19 05:40:49,540][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 05:40:52,335][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=2755587, ip=115.145.172.224, actor_id=74c709537b1b0ff8d220f38401000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f3a60179930>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_vgg16/fedavg_vgg16/client.py", line 91, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=2755587, ip=115.145.172.224, actor_id=74c709537b1b0ff8d220f38401000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f3a60179930>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-09-19 05:40:52,336][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=2755587, ip=115.145.172.224, actor_id=74c709537b1b0ff8d220f38401000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f3a60179930>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_vgg16/fedavg_vgg16/client.py", line 91, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=2755587, ip=115.145.172.224, actor_id=74c709537b1b0ff8d220f38401000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f3a60179930>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-09-19 05:41:01,911][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-09-19 05:41:13,211][flwr][INFO] - fit progress: (31, 814.8991141319275, {'accuracy': 0.19467991815258695}, 956.6596453329548)
[2024-09-19 05:41:13,212][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 05:41:16,605][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 05:41:16,605][flwr][INFO] - 
[2024-09-19 05:41:16,606][flwr][INFO] - [ROUND 32]
[2024-09-19 05:41:16,606][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 05:41:40,471][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 05:41:51,316][flwr][INFO] - fit progress: (32, 223.40188932418823, {'accuracy': 0.29318912598655367}, 994.7641542716883)
[2024-09-19 05:41:51,316][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 05:41:54,451][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 05:41:54,451][flwr][INFO] - 
[2024-09-19 05:41:54,451][flwr][INFO] - [ROUND 33]
[2024-09-19 05:41:54,452][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 05:42:14,338][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 05:42:25,516][flwr][INFO] - fit progress: (33, 172.379714012146, {'accuracy': 0.256357790119848}, 1028.964542041067)
[2024-09-19 05:42:25,517][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 05:42:28,639][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 05:42:28,639][flwr][INFO] - 
[2024-09-19 05:42:28,640][flwr][INFO] - [ROUND 34]
[2024-09-19 05:42:28,640][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 05:42:30,973][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=2755587, ip=115.145.172.224, actor_id=74c709537b1b0ff8d220f38401000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f3a60179930>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_vgg16/fedavg_vgg16/client.py", line 91, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=2755587, ip=115.145.172.224, actor_id=74c709537b1b0ff8d220f38401000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f3a60179930>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-09-19 05:42:30,974][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=2755587, ip=115.145.172.224, actor_id=74c709537b1b0ff8d220f38401000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f3a60179930>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_vgg16/fedavg_vgg16/client.py", line 91, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=2755587, ip=115.145.172.224, actor_id=74c709537b1b0ff8d220f38401000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f3a60179930>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-09-19 05:42:44,373][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-09-19 05:42:54,994][flwr][INFO] - fit progress: (34, 188.85340213775635, {'accuracy': 0.33177433498976905}, 1058.4423263077624)
[2024-09-19 05:42:54,995][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 05:42:58,143][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 05:42:58,143][flwr][INFO] - 
[2024-09-19 05:42:58,143][flwr][INFO] - [ROUND 35]
[2024-09-19 05:42:58,143][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 05:43:17,523][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 05:43:28,671][flwr][INFO] - fit progress: (35, 220.37343037128448, {'accuracy': 0.22128032738965214}, 1092.11872565886)
[2024-09-19 05:43:28,671][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 05:43:31,831][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 05:43:31,831][flwr][INFO] - 
[2024-09-19 05:43:31,831][flwr][INFO] - [ROUND 36]
[2024-09-19 05:43:31,831][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 05:43:50,446][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 05:44:01,828][flwr][INFO] - fit progress: (36, 204.7879763841629, {'accuracy': 0.34200526161940953}, 1125.275815865025)
[2024-09-19 05:44:01,828][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 05:44:04,742][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 05:44:04,743][flwr][INFO] - 
[2024-09-19 05:44:04,743][flwr][INFO] - [ROUND 37]
[2024-09-19 05:44:04,743][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 05:44:20,199][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 05:44:31,788][flwr][INFO] - fit progress: (37, 239.3770271539688, {'accuracy': 0.3744519146448407}, 1155.2363072768785)
[2024-09-19 05:44:31,788][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 05:44:34,889][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 05:44:34,890][flwr][INFO] - 
[2024-09-19 05:44:34,890][flwr][INFO] - [ROUND 38]
[2024-09-19 05:44:34,890][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 05:44:53,308][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 05:45:03,448][flwr][INFO] - fit progress: (38, 391.0763895511627, {'accuracy': 0.26571178018123354}, 1186.8959079738706)
[2024-09-19 05:45:03,448][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 05:45:06,939][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 05:45:06,939][flwr][INFO] - 
[2024-09-19 05:45:06,939][flwr][INFO] - [ROUND 39]
[2024-09-19 05:45:06,940][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 05:45:22,365][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 05:45:32,469][flwr][INFO] - fit progress: (39, 191.99643087387085, {'accuracy': 0.1335866705641625}, 1215.9168988880701)
[2024-09-19 05:45:32,469][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 05:45:35,516][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 05:45:35,516][flwr][INFO] - 
[2024-09-19 05:45:35,516][flwr][INFO] - [ROUND 40]
[2024-09-19 05:45:35,517][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 05:45:57,671][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 05:46:07,678][flwr][INFO] - fit progress: (40, 191.66151893138885, {'accuracy': 0.3770827243496054}, 1251.1262593478896)
[2024-09-19 05:46:07,678][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 05:46:10,923][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 05:46:10,923][flwr][INFO] - 
[2024-09-19 05:46:10,923][flwr][INFO] - [ROUND 41]
[2024-09-19 05:46:10,923][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 05:46:27,775][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 05:46:37,888][flwr][INFO] - fit progress: (41, 208.0507106781006, {'accuracy': 0.3975445776088863}, 1281.3363098427653)
[2024-09-19 05:46:37,888][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 05:46:40,908][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 05:46:40,909][flwr][INFO] - 
[2024-09-19 05:46:40,909][flwr][INFO] - [ROUND 42]
[2024-09-19 05:46:40,909][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 05:46:52,397][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=2755587, ip=115.145.172.224, actor_id=74c709537b1b0ff8d220f38401000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f3a60179930>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_vgg16/fedavg_vgg16/client.py", line 91, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=2755587, ip=115.145.172.224, actor_id=74c709537b1b0ff8d220f38401000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f3a60179930>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-09-19 05:46:52,397][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=2755587, ip=115.145.172.224, actor_id=74c709537b1b0ff8d220f38401000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f3a60179930>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_vgg16/fedavg_vgg16/client.py", line 91, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=2755587, ip=115.145.172.224, actor_id=74c709537b1b0ff8d220f38401000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f3a60179930>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-09-19 05:46:54,460][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-09-19 05:47:04,390][flwr][INFO] - fit progress: (42, 184.6286779642105, {'accuracy': 0.29114294066062557}, 1307.8379392507486)
[2024-09-19 05:47:04,390][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 05:47:07,616][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 05:47:07,616][flwr][INFO] - 
[2024-09-19 05:47:07,616][flwr][INFO] - [ROUND 43]
[2024-09-19 05:47:07,616][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 05:47:25,184][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 05:47:35,418][flwr][INFO] - fit progress: (43, 182.78794407844543, {'accuracy': 0.38409821689564455}, 1338.8666183580644)
[2024-09-19 05:47:35,419][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 05:47:38,518][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 05:47:38,518][flwr][INFO] - 
[2024-09-19 05:47:38,518][flwr][INFO] - [ROUND 44]
[2024-09-19 05:47:38,518][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 05:47:56,731][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 05:48:07,008][flwr][INFO] - fit progress: (44, 147.51084768772125, {'accuracy': 0.4671148786904414}, 1370.4562623817474)
[2024-09-19 05:48:07,008][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 05:48:10,085][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 05:48:10,085][flwr][INFO] - 
[2024-09-19 05:48:10,085][flwr][INFO] - [ROUND 45]
[2024-09-19 05:48:10,085][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 05:48:23,431][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 05:48:34,472][flwr][INFO] - fit progress: (45, 224.15455651283264, {'accuracy': 0.29026600409237063}, 1397.92034688266)
[2024-09-19 05:48:34,472][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 05:48:37,716][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 05:48:37,717][flwr][INFO] - 
[2024-09-19 05:48:37,717][flwr][INFO] - [ROUND 46]
[2024-09-19 05:48:37,717][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 05:48:51,050][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 05:49:02,004][flwr][INFO] - fit progress: (46, 248.86411702632904, {'accuracy': 0.24904998538439052}, 1425.4523732569069)
[2024-09-19 05:49:02,010][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 05:49:05,199][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 05:49:05,199][flwr][INFO] - 
[2024-09-19 05:49:05,199][flwr][INFO] - [ROUND 47]
[2024-09-19 05:49:05,199][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 05:49:23,571][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 05:49:33,671][flwr][INFO] - fit progress: (47, 267.44094955921173, {'accuracy': 0.36100555393159894}, 1457.118720157072)
[2024-09-19 05:49:33,671][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 05:49:37,422][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 05:49:37,423][flwr][INFO] - 
[2024-09-19 05:49:37,423][flwr][INFO] - [ROUND 48]
[2024-09-19 05:49:37,423][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 05:49:53,742][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 05:50:03,836][flwr][INFO] - fit progress: (48, 145.7940800189972, {'accuracy': 0.47939199064600996}, 1487.2842113920487)
[2024-09-19 05:50:03,836][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 05:50:06,902][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 05:50:06,902][flwr][INFO] - 
[2024-09-19 05:50:06,902][flwr][INFO] - [ROUND 49]
[2024-09-19 05:50:06,902][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 05:50:19,893][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 05:50:31,309][flwr][INFO] - fit progress: (49, 330.93445432186127, {'accuracy': 0.30985092078339666}, 1514.7575808018446)
[2024-09-19 05:50:31,310][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 05:50:34,342][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 05:50:34,342][flwr][INFO] - 
[2024-09-19 05:50:34,342][flwr][INFO] - [ROUND 50]
[2024-09-19 05:50:34,343][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 05:50:42,959][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=2755587, ip=115.145.172.224, actor_id=74c709537b1b0ff8d220f38401000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f3a60179930>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_vgg16/fedavg_vgg16/client.py", line 91, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=2755587, ip=115.145.172.224, actor_id=74c709537b1b0ff8d220f38401000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f3a60179930>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-09-19 05:50:42,959][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=2755587, ip=115.145.172.224, actor_id=74c709537b1b0ff8d220f38401000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f3a60179930>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_vgg16/fedavg_vgg16/client.py", line 91, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=2755587, ip=115.145.172.224, actor_id=74c709537b1b0ff8d220f38401000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f3a60179930>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-09-19 05:50:46,874][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-09-19 05:50:56,630][flwr][INFO] - fit progress: (50, 196.3268893957138, {'accuracy': 0.33177433498976905}, 1540.077941069845)
[2024-09-19 05:50:56,630][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 05:51:00,260][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 05:51:00,260][flwr][INFO] - 
[2024-09-19 05:51:00,260][flwr][INFO] - [ROUND 51]
[2024-09-19 05:51:00,260][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 05:51:03,233][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=2755588, ip=115.145.172.224, actor_id=06771556b6217d876bf7275301000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f14f8275960>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_vgg16/fedavg_vgg16/client.py", line 91, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=2755588, ip=115.145.172.224, actor_id=06771556b6217d876bf7275301000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f14f8275960>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-09-19 05:51:03,234][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=2755588, ip=115.145.172.224, actor_id=06771556b6217d876bf7275301000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f14f8275960>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_vgg16/fedavg_vgg16/client.py", line 91, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=2755588, ip=115.145.172.224, actor_id=06771556b6217d876bf7275301000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f14f8275960>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-09-19 05:51:15,587][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-09-19 05:51:25,792][flwr][INFO] - fit progress: (51, 323.4802031517029, {'accuracy': 0.2136802104647764}, 1569.2403455469757)
[2024-09-19 05:51:25,792][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 05:51:29,075][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 05:51:29,076][flwr][INFO] - 
[2024-09-19 05:51:29,076][flwr][INFO] - [ROUND 52]
[2024-09-19 05:51:29,076][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 05:51:46,759][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 05:51:57,853][flwr][INFO] - fit progress: (52, 177.502006649971, {'accuracy': 0.24232680502776965}, 1601.3008765387349)
[2024-09-19 05:51:57,854][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 05:52:00,916][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 05:52:00,916][flwr][INFO] - 
[2024-09-19 05:52:00,916][flwr][INFO] - [ROUND 53]
[2024-09-19 05:52:00,917][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 05:52:14,126][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 05:52:25,607][flwr][INFO] - fit progress: (53, 197.32806944847107, {'accuracy': 0.27038877521192634}, 1629.0547351278365)
[2024-09-19 05:52:25,611][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 05:52:28,926][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 05:52:28,927][flwr][INFO] - 
[2024-09-19 05:52:28,927][flwr][INFO] - [ROUND 54]
[2024-09-19 05:52:28,927][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 05:52:48,128][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 05:52:59,712][flwr][INFO] - fit progress: (54, 167.42883849143982, {'accuracy': 0.40660625548085355}, 1663.1603727727197)
[2024-09-19 05:52:59,713][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 05:53:03,284][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 05:53:03,285][flwr][INFO] - 
[2024-09-19 05:53:03,285][flwr][INFO] - [ROUND 55]
[2024-09-19 05:53:03,285][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 05:53:19,533][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 05:53:30,642][flwr][INFO] - fit progress: (55, 167.63740944862366, {'accuracy': 0.397252265419468}, 1694.0905724698678)
[2024-09-19 05:53:30,643][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 05:53:33,837][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 05:53:33,838][flwr][INFO] - 
[2024-09-19 05:53:33,838][flwr][INFO] - [ROUND 56]
[2024-09-19 05:53:33,838][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 05:53:53,984][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 05:54:05,407][flwr][INFO] - fit progress: (56, 148.92517751455307, {'accuracy': 0.4837766734872844}, 1728.8548055249266)
[2024-09-19 05:54:05,407][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 05:54:08,732][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 05:54:08,732][flwr][INFO] - 
[2024-09-19 05:54:08,732][flwr][INFO] - [ROUND 57]
[2024-09-19 05:54:08,732][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 05:54:26,619][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 05:54:37,602][flwr][INFO] - fit progress: (57, 163.3907800912857, {'accuracy': 0.3572054954691611}, 1761.0497210556641)
[2024-09-19 05:54:37,602][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 05:54:40,787][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 05:54:40,788][flwr][INFO] - 
[2024-09-19 05:54:40,788][flwr][INFO] - [ROUND 58]
[2024-09-19 05:54:40,788][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 05:55:00,252][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 05:55:11,556][flwr][INFO] - fit progress: (58, 186.57170450687408, {'accuracy': 0.36451330020461853}, 1795.0041551687755)
[2024-09-19 05:55:11,556][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 05:55:14,931][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 05:55:14,931][flwr][INFO] - 
[2024-09-19 05:55:14,931][flwr][INFO] - [ROUND 59]
[2024-09-19 05:55:14,932][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 05:55:30,567][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 05:55:41,138][flwr][INFO] - fit progress: (59, 174.60418462753296, {'accuracy': 0.30575855013154046}, 1824.5858730641194)
[2024-09-19 05:55:41,138][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 05:55:44,502][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 05:55:44,502][flwr][INFO] - 
[2024-09-19 05:55:44,502][flwr][INFO] - [ROUND 60]
[2024-09-19 05:55:44,502][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 05:56:00,755][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 05:56:11,075][flwr][INFO] - fit progress: (60, 284.9017996788025, {'accuracy': 0.3490207541654487}, 1854.5231313901022)
[2024-09-19 05:56:11,075][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 05:56:14,352][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 05:56:14,353][flwr][INFO] - 
[2024-09-19 05:56:14,353][flwr][INFO] - [ROUND 61]
[2024-09-19 05:56:14,353][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 05:56:26,118][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 05:56:36,891][flwr][INFO] - fit progress: (61, 173.7874743938446, {'accuracy': 0.27360420929552765}, 1880.3394699320197)
[2024-09-19 05:56:36,892][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 05:56:40,164][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 05:56:40,164][flwr][INFO] - 
[2024-09-19 05:56:40,164][flwr][INFO] - [ROUND 62]
[2024-09-19 05:56:40,164][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 05:56:54,159][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 05:57:05,389][flwr][INFO] - fit progress: (62, 165.44527900218964, {'accuracy': 0.38760596316866414}, 1908.836817116011)
[2024-09-19 05:57:05,389][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 05:57:08,486][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 05:57:08,486][flwr][INFO] - 
[2024-09-19 05:57:08,486][flwr][INFO] - [ROUND 63]
[2024-09-19 05:57:08,487][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 05:57:25,787][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 05:57:36,530][flwr][INFO] - fit progress: (63, 146.27642852067947, {'accuracy': 0.4381759719380298}, 1939.977877842728)
[2024-09-19 05:57:36,530][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 05:57:39,633][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 05:57:39,633][flwr][INFO] - 
[2024-09-19 05:57:39,634][flwr][INFO] - [ROUND 64]
[2024-09-19 05:57:39,634][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 05:57:55,321][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 05:58:05,997][flwr][INFO] - fit progress: (64, 178.88250768184662, {'accuracy': 0.36217480268927216}, 1969.445035542827)
[2024-09-19 05:58:05,997][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 05:58:09,010][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 05:58:09,010][flwr][INFO] - 
[2024-09-19 05:58:09,010][flwr][INFO] - [ROUND 65]
[2024-09-19 05:58:09,010][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 05:58:24,512][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 05:58:34,716][flwr][INFO] - fit progress: (65, 133.34793955087662, {'accuracy': 0.5346389944460684}, 1998.1640663649887)
[2024-09-19 05:58:34,716][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 05:58:37,938][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 05:58:37,938][flwr][INFO] - 
[2024-09-19 05:58:37,938][flwr][INFO] - [ROUND 66]
[2024-09-19 05:58:37,938][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 05:58:57,519][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 05:59:07,864][flwr][INFO] - fit progress: (66, 184.54650449752808, {'accuracy': 0.39228295819935693}, 2031.3120194608346)
[2024-09-19 05:59:07,864][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 05:59:11,088][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 05:59:11,088][flwr][INFO] - 
[2024-09-19 05:59:11,088][flwr][INFO] - [ROUND 67]
[2024-09-19 05:59:11,088][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 05:59:24,746][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 05:59:34,996][flwr][INFO] - fit progress: (67, 197.4779441356659, {'accuracy': 0.33966676410406316}, 2058.4440580918454)
[2024-09-19 05:59:34,996][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 05:59:38,368][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 05:59:38,368][flwr][INFO] - 
[2024-09-19 05:59:38,369][flwr][INFO] - [ROUND 68]
[2024-09-19 05:59:38,369][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 05:59:59,137][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 06:00:09,971][flwr][INFO] - fit progress: (68, 191.18723273277283, {'accuracy': 0.4405144694533762}, 2093.418867825996)
[2024-09-19 06:00:09,971][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 06:00:13,155][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 06:00:13,156][flwr][INFO] - 
[2024-09-19 06:00:13,156][flwr][INFO] - [ROUND 69]
[2024-09-19 06:00:13,156][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 06:00:15,834][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=2755587, ip=115.145.172.224, actor_id=74c709537b1b0ff8d220f38401000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f3a60179930>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_vgg16/fedavg_vgg16/client.py", line 91, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=2755587, ip=115.145.172.224, actor_id=74c709537b1b0ff8d220f38401000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f3a60179930>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-09-19 06:00:15,835][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=2755587, ip=115.145.172.224, actor_id=74c709537b1b0ff8d220f38401000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f3a60179930>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_vgg16/fedavg_vgg16/client.py", line 91, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=2755587, ip=115.145.172.224, actor_id=74c709537b1b0ff8d220f38401000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f3a60179930>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-09-19 06:00:26,710][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-09-19 06:00:37,221][flwr][INFO] - fit progress: (69, 203.3732384443283, {'accuracy': 0.35691318327974275}, 2120.669339506887)
[2024-09-19 06:00:37,221][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 06:00:40,391][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 06:00:40,391][flwr][INFO] - 
[2024-09-19 06:00:40,391][flwr][INFO] - [ROUND 70]
[2024-09-19 06:00:40,392][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 06:00:57,605][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 06:01:08,388][flwr][INFO] - fit progress: (70, 166.5615760087967, {'accuracy': 0.4329143525285004}, 2151.836326654069)
[2024-09-19 06:01:08,389][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 06:01:11,544][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 06:01:11,544][flwr][INFO] - 
[2024-09-19 06:01:11,544][flwr][INFO] - [ROUND 71]
[2024-09-19 06:01:11,544][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 06:01:25,621][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 06:01:35,931][flwr][INFO] - fit progress: (71, 180.57121467590332, {'accuracy': 0.4609763227126571}, 2179.3790087350644)
[2024-09-19 06:01:35,931][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 06:01:39,092][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 06:01:39,092][flwr][INFO] - 
[2024-09-19 06:01:39,092][flwr][INFO] - [ROUND 72]
[2024-09-19 06:01:39,092][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 06:01:55,938][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 06:02:06,103][flwr][INFO] - fit progress: (72, 140.18981957435608, {'accuracy': 0.45103770827243495}, 2209.551447683014)
[2024-09-19 06:02:06,104][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 06:02:09,319][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 06:02:09,319][flwr][INFO] - 
[2024-09-19 06:02:09,319][flwr][INFO] - [ROUND 73]
[2024-09-19 06:02:09,320][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 06:02:34,904][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 06:02:45,866][flwr][INFO] - fit progress: (73, 177.37013632059097, {'accuracy': 0.4410990938322128}, 2249.314372847788)
[2024-09-19 06:02:45,867][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 06:02:49,012][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 06:02:49,013][flwr][INFO] - 
[2024-09-19 06:02:49,013][flwr][INFO] - [ROUND 74]
[2024-09-19 06:02:49,013][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 06:03:08,743][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 06:03:18,959][flwr][INFO] - fit progress: (74, 207.1789540052414, {'accuracy': 0.3680210464776381}, 2282.4071485647)
[2024-09-19 06:03:18,959][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 06:03:22,554][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 06:03:22,554][flwr][INFO] - 
[2024-09-19 06:03:22,554][flwr][INFO] - [ROUND 75]
[2024-09-19 06:03:22,554][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 06:03:34,964][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 06:03:45,293][flwr][INFO] - fit progress: (75, 188.61102485656738, {'accuracy': 0.4513300204618533}, 2308.7410025298595)
[2024-09-19 06:03:45,293][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 06:03:48,313][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 06:03:48,314][flwr][INFO] - 
[2024-09-19 06:03:48,314][flwr][INFO] - [ROUND 76]
[2024-09-19 06:03:48,314][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 06:04:03,679][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 06:04:14,251][flwr][INFO] - fit progress: (76, 164.9422169327736, {'accuracy': 0.42356036246711487}, 2337.698923008982)
[2024-09-19 06:04:14,251][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 06:04:17,547][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 06:04:17,547][flwr][INFO] - 
[2024-09-19 06:04:17,548][flwr][INFO] - [ROUND 77]
[2024-09-19 06:04:17,548][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 06:04:37,494][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 06:04:47,604][flwr][INFO] - fit progress: (77, 158.2155829668045, {'accuracy': 0.41332943583747445}, 2371.0524700707756)
[2024-09-19 06:04:47,605][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 06:04:50,734][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 06:04:50,734][flwr][INFO] - 
[2024-09-19 06:04:50,734][flwr][INFO] - [ROUND 78]
[2024-09-19 06:04:50,735][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 06:05:07,292][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 06:05:17,543][flwr][INFO] - fit progress: (78, 155.5544172525406, {'accuracy': 0.42356036246711487}, 2400.9917078837752)
[2024-09-19 06:05:17,544][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 06:05:21,150][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 06:05:21,150][flwr][INFO] - 
[2024-09-19 06:05:21,151][flwr][INFO] - [ROUND 79]
[2024-09-19 06:05:21,151][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 06:05:24,190][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=2755587, ip=115.145.172.224, actor_id=74c709537b1b0ff8d220f38401000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f3a60179930>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_vgg16/fedavg_vgg16/client.py", line 91, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=2755587, ip=115.145.172.224, actor_id=74c709537b1b0ff8d220f38401000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f3a60179930>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-09-19 06:05:24,190][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=2755587, ip=115.145.172.224, actor_id=74c709537b1b0ff8d220f38401000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f3a60179930>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_vgg16/fedavg_vgg16/client.py", line 91, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=2755587, ip=115.145.172.224, actor_id=74c709537b1b0ff8d220f38401000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f3a60179930>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-09-19 06:05:39,847][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-09-19 06:05:50,090][flwr][INFO] - fit progress: (79, 172.67417401075363, {'accuracy': 0.5399006138555977}, 2433.5382596799172)
[2024-09-19 06:05:50,090][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 06:05:53,342][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 06:05:53,343][flwr][INFO] - 
[2024-09-19 06:05:53,343][flwr][INFO] - [ROUND 80]
[2024-09-19 06:05:53,343][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 06:06:10,199][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 06:06:20,413][flwr][INFO] - fit progress: (80, 225.7377132177353, {'accuracy': 0.388482899736919}, 2463.8612528429367)
[2024-09-19 06:06:20,413][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 06:06:23,683][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 06:06:23,684][flwr][INFO] - 
[2024-09-19 06:06:23,684][flwr][INFO] - [ROUND 81]
[2024-09-19 06:06:23,684][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 06:06:36,215][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 06:06:46,396][flwr][INFO] - fit progress: (81, 153.15514361858368, {'accuracy': 0.413914060216311}, 2489.8443924230523)
[2024-09-19 06:06:46,396][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 06:06:49,593][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 06:06:49,593][flwr][INFO] - 
[2024-09-19 06:06:49,593][flwr][INFO] - [ROUND 82]
[2024-09-19 06:06:49,593][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 06:07:03,424][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 06:07:13,585][flwr][INFO] - fit progress: (82, 186.14743673801422, {'accuracy': 0.36363636363636365}, 2517.033223350998)
[2024-09-19 06:07:13,585][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 06:07:16,906][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 06:07:16,907][flwr][INFO] - 
[2024-09-19 06:07:16,907][flwr][INFO] - [ROUND 83]
[2024-09-19 06:07:16,907][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 06:07:30,808][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 06:07:40,878][flwr][INFO] - fit progress: (83, 197.93535828590393, {'accuracy': 0.2809120140309851}, 2544.3260563048534)
[2024-09-19 06:07:40,878][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 06:07:44,038][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 06:07:44,038][flwr][INFO] - 
[2024-09-19 06:07:44,038][flwr][INFO] - [ROUND 84]
[2024-09-19 06:07:44,039][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 06:08:03,483][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 06:08:13,522][flwr][INFO] - fit progress: (84, 139.87571793794632, {'accuracy': 0.5095001461560947}, 2576.9703779239208)
[2024-09-19 06:08:13,523][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 06:08:17,406][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 06:08:17,407][flwr][INFO] - 
[2024-09-19 06:08:17,407][flwr][INFO] - [ROUND 85]
[2024-09-19 06:08:17,407][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 06:08:37,554][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 06:08:47,971][flwr][INFO] - fit progress: (85, 267.81910490989685, {'accuracy': 0.36275942706810876}, 2611.419328633696)
[2024-09-19 06:08:47,971][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 06:08:51,155][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 06:08:51,155][flwr][INFO] - 
[2024-09-19 06:08:51,155][flwr][INFO] - [ROUND 86]
[2024-09-19 06:08:51,155][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 06:09:07,681][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 06:09:18,046][flwr][INFO] - fit progress: (86, 198.19132900238037, {'accuracy': 0.31189710610932475}, 2641.4940518988296)
[2024-09-19 06:09:18,046][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 06:09:21,174][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 06:09:21,175][flwr][INFO] - 
[2024-09-19 06:09:21,175][flwr][INFO] - [ROUND 87]
[2024-09-19 06:09:21,175][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 06:09:38,504][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 06:09:48,676][flwr][INFO] - fit progress: (87, 149.7783686518669, {'accuracy': 0.4586378251973107}, 2672.124545924831)
[2024-09-19 06:09:48,677][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 06:09:52,186][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 06:09:52,186][flwr][INFO] - 
[2024-09-19 06:09:52,186][flwr][INFO] - [ROUND 88]
[2024-09-19 06:09:52,186][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 06:10:11,646][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 06:10:21,787][flwr][INFO] - fit progress: (88, 160.24197226762772, {'accuracy': 0.45629932768196435}, 2705.234806952998)
[2024-09-19 06:10:21,787][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 06:10:24,806][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 06:10:24,806][flwr][INFO] - 
[2024-09-19 06:10:24,806][flwr][INFO] - [ROUND 89]
[2024-09-19 06:10:24,807][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 06:10:42,041][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 06:10:54,841][flwr][INFO] - fit progress: (89, 156.7819185256958, {'accuracy': 0.4595147617655656}, 2738.2897036238573)
[2024-09-19 06:10:54,842][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 06:10:56,412][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=2755588, ip=115.145.172.224, actor_id=06771556b6217d876bf7275301000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f14f8275960>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_vgg16/fedavg_vgg16/client.py", line 91, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=2755588, ip=115.145.172.224, actor_id=06771556b6217d876bf7275301000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f14f8275960>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-09-19 06:10:56,412][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=2755588, ip=115.145.172.224, actor_id=06771556b6217d876bf7275301000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f14f8275960>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_vgg16/fedavg_vgg16/client.py", line 91, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=2755588, ip=115.145.172.224, actor_id=06771556b6217d876bf7275301000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f14f8275960>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-09-19 06:10:58,056][flwr][INFO] - aggregate_evaluate: received 1 results and 1 failures
[2024-09-19 06:10:58,056][flwr][INFO] - 
[2024-09-19 06:10:58,057][flwr][INFO] - [ROUND 90]
[2024-09-19 06:10:58,057][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 06:11:12,352][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 06:11:22,491][flwr][INFO] - fit progress: (90, 148.33892804384232, {'accuracy': 0.4934229757380883}, 2765.939021439757)
[2024-09-19 06:11:22,491][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 06:11:25,662][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 06:11:25,663][flwr][INFO] - 
[2024-09-19 06:11:25,663][flwr][INFO] - [ROUND 91]
[2024-09-19 06:11:25,663][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 06:11:43,171][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 06:11:53,985][flwr][INFO] - fit progress: (91, 161.9329262971878, {'accuracy': 0.4165448699210757}, 2797.432974819094)
[2024-09-19 06:11:53,985][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 06:11:57,138][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 06:11:57,138][flwr][INFO] - 
[2024-09-19 06:11:57,139][flwr][INFO] - [ROUND 92]
[2024-09-19 06:11:57,139][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 06:12:14,970][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 06:12:25,450][flwr][INFO] - fit progress: (92, 131.0054919719696, {'accuracy': 0.5080385852090032}, 2828.897889730986)
[2024-09-19 06:12:25,450][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 06:12:29,077][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 06:12:29,077][flwr][INFO] - 
[2024-09-19 06:12:29,077][flwr][INFO] - [ROUND 93]
[2024-09-19 06:12:29,077][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 06:12:45,516][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 06:12:56,256][flwr][INFO] - fit progress: (93, 222.83596110343933, {'accuracy': 0.33908213972522655}, 2859.7045927071013)
[2024-09-19 06:12:56,257][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 06:12:59,235][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 06:12:59,235][flwr][INFO] - 
[2024-09-19 06:12:59,236][flwr][INFO] - [ROUND 94]
[2024-09-19 06:12:59,236][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 06:13:12,494][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=2755588, ip=115.145.172.224, actor_id=06771556b6217d876bf7275301000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f14f8275960>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_vgg16/fedavg_vgg16/client.py", line 91, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=2755588, ip=115.145.172.224, actor_id=06771556b6217d876bf7275301000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f14f8275960>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-09-19 06:13:12,494][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=2755588, ip=115.145.172.224, actor_id=06771556b6217d876bf7275301000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f14f8275960>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_vgg16/fedavg_vgg16/client.py", line 91, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=2755588, ip=115.145.172.224, actor_id=06771556b6217d876bf7275301000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f14f8275960>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-09-19 06:13:12,814][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-09-19 06:13:22,904][flwr][INFO] - fit progress: (94, 153.0809336900711, {'accuracy': 0.43934522069570303}, 2886.35242861975)
[2024-09-19 06:13:22,905][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 06:13:26,169][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 06:13:26,170][flwr][INFO] - 
[2024-09-19 06:13:26,170][flwr][INFO] - [ROUND 95]
[2024-09-19 06:13:26,170][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 06:13:42,520][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 06:13:52,846][flwr][INFO] - fit progress: (95, 151.32084584236145, {'accuracy': 0.5074539608301666}, 2916.294001200702)
[2024-09-19 06:13:52,846][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 06:13:56,262][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 06:13:56,262][flwr][INFO] - 
[2024-09-19 06:13:56,263][flwr][INFO] - [ROUND 96]
[2024-09-19 06:13:56,263][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 06:14:10,678][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 06:14:21,453][flwr][INFO] - fit progress: (96, 189.7887372970581, {'accuracy': 0.4007600116924876}, 2944.901706307661)
[2024-09-19 06:14:21,454][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 06:14:24,984][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 06:14:24,984][flwr][INFO] - 
[2024-09-19 06:14:24,984][flwr][INFO] - [ROUND 97]
[2024-09-19 06:14:24,984][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 06:14:38,181][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 06:14:49,293][flwr][INFO] - fit progress: (97, 220.39284706115723, {'accuracy': 0.3256357790119848}, 2972.741604251787)
[2024-09-19 06:14:49,294][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 06:14:52,523][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 06:14:52,524][flwr][INFO] - 
[2024-09-19 06:14:52,524][flwr][INFO] - [ROUND 98]
[2024-09-19 06:14:52,524][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 06:15:10,606][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 06:15:20,580][flwr][INFO] - fit progress: (98, 191.77582186460495, {'accuracy': 0.3040046769950307}, 3004.0284189027734)
[2024-09-19 06:15:20,580][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 06:15:23,957][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 06:15:23,958][flwr][INFO] - 
[2024-09-19 06:15:23,958][flwr][INFO] - [ROUND 99]
[2024-09-19 06:15:23,958][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 06:15:48,490][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 06:15:58,568][flwr][INFO] - fit progress: (99, 261.2749480009079, {'accuracy': 0.21806489330605086}, 3042.0166654898785)
[2024-09-19 06:15:58,569][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 06:16:01,951][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 06:16:01,951][flwr][INFO] - 
[2024-09-19 06:16:01,951][flwr][INFO] - [ROUND 100]
[2024-09-19 06:16:01,952][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-19 06:16:18,296][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-19 06:16:28,827][flwr][INFO] - fit progress: (100, 164.25777125358582, {'accuracy': 0.42297573808827826}, 3072.275208217092)
[2024-09-19 06:16:28,827][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-19 06:16:32,223][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-19 06:16:32,390][flwr][INFO] - 
[2024-09-19 06:16:32,390][flwr][INFO] - [SUMMARY]
[2024-09-19 06:16:32,390][flwr][INFO] - Run finished 100 round(s) in 3075.67s
[2024-09-19 06:16:32,393][flwr][INFO] - 	History (loss, distributed):
[2024-09-19 06:16:32,393][flwr][INFO] - 		round 1: 4.256193930688112
[2024-09-19 06:16:32,393][flwr][INFO] - 		round 2: 3.295921972819737
[2024-09-19 06:16:32,393][flwr][INFO] - 		round 3: 2.169230302174886
[2024-09-19 06:16:32,394][flwr][INFO] - 		round 4: 1.7280352399462746
[2024-09-19 06:16:32,394][flwr][INFO] - 		round 5: 1.749114677661986
[2024-09-19 06:16:32,394][flwr][INFO] - 		round 6: 1.3930694051086903
[2024-09-19 06:16:32,394][flwr][INFO] - 		round 7: 2.391337528461363
[2024-09-19 06:16:32,394][flwr][INFO] - 		round 8: 3.544004939323248
[2024-09-19 06:16:32,394][flwr][INFO] - 		round 9: 2.038073610777807
[2024-09-19 06:16:32,394][flwr][INFO] - 		round 10: 2.7497711181640625
[2024-09-19 06:16:32,394][flwr][INFO] - 		round 11: 1.14986269438968
[2024-09-19 06:16:32,394][flwr][INFO] - 		round 12: 3.6232323681606964
[2024-09-19 06:16:32,394][flwr][INFO] - 		round 13: 1.137270674109459
[2024-09-19 06:16:32,394][flwr][INFO] - 		round 14: 7.601112747192383
[2024-09-19 06:16:32,394][flwr][INFO] - 		round 15: 3.097193922751989
[2024-09-19 06:16:32,394][flwr][INFO] - 		round 16: 2.5539559456239265
[2024-09-19 06:16:32,394][flwr][INFO] - 		round 17: 2.357977264067706
[2024-09-19 06:16:32,394][flwr][INFO] - 		round 18: 1.6574716866016388
[2024-09-19 06:16:32,394][flwr][INFO] - 		round 19: 1.6070193000461743
[2024-09-19 06:16:32,394][flwr][INFO] - 		round 20: 6.445709067583084
[2024-09-19 06:16:32,394][flwr][INFO] - 		round 21: 2.1622804144154424
[2024-09-19 06:16:32,394][flwr][INFO] - 		round 22: 1.7755177736282348
[2024-09-19 06:16:32,394][flwr][INFO] - 		round 23: 1.3125581928853238
[2024-09-19 06:16:32,394][flwr][INFO] - 		round 24: 1.4046194288465712
[2024-09-19 06:16:32,394][flwr][INFO] - 		round 25: 3.255386882358127
[2024-09-19 06:16:32,395][flwr][INFO] - 		round 26: 2.2203512051526237
[2024-09-19 06:16:32,395][flwr][INFO] - 		round 27: 3.2500748257887992
[2024-09-19 06:16:32,395][flwr][INFO] - 		round 28: 2.614635531495257
[2024-09-19 06:16:32,395][flwr][INFO] - 		round 29: 2.0897645235061644
[2024-09-19 06:16:32,395][flwr][INFO] - 		round 30: 3.937116601250388
[2024-09-19 06:16:32,395][flwr][INFO] - 		round 31: 9.93656818683331
[2024-09-19 06:16:32,395][flwr][INFO] - 		round 32: 2.4315745269550995
[2024-09-19 06:16:32,395][flwr][INFO] - 		round 33: 1.1340547970363073
[2024-09-19 06:16:32,395][flwr][INFO] - 		round 34: 2.1248327578817094
[2024-09-19 06:16:32,395][flwr][INFO] - 		round 35: 2.161099157025737
[2024-09-19 06:16:32,395][flwr][INFO] - 		round 36: 2.32835050798812
[2024-09-19 06:16:32,395][flwr][INFO] - 		round 37: 1.0149159696367052
[2024-09-19 06:16:32,395][flwr][INFO] - 		round 38: 4.091151090768667
[2024-09-19 06:16:32,395][flwr][INFO] - 		round 39: 1.899132265882977
[2024-09-19 06:16:32,395][flwr][INFO] - 		round 40: 1.3955652767961675
[2024-09-19 06:16:32,395][flwr][INFO] - 		round 41: 2.775728225708008
[2024-09-19 06:16:32,395][flwr][INFO] - 		round 42: 2.7163411180178323
[2024-09-19 06:16:32,395][flwr][INFO] - 		round 43: 1.6616769082405989
[2024-09-19 06:16:32,395][flwr][INFO] - 		round 44: 0.9875928326086565
[2024-09-19 06:16:32,395][flwr][INFO] - 		round 45: 3.559025764465332
[2024-09-19 06:16:32,395][flwr][INFO] - 		round 46: 2.26388126373291
[2024-09-19 06:16:32,395][flwr][INFO] - 		round 47: 1.7986669849466395
[2024-09-19 06:16:32,396][flwr][INFO] - 		round 48: 1.0022702379660173
[2024-09-19 06:16:32,396][flwr][INFO] - 		round 49: 3.2623368687927723
[2024-09-19 06:16:32,396][flwr][INFO] - 		round 50: 2.036707004504417
[2024-09-19 06:16:32,396][flwr][INFO] - 		round 51: 3.0209658185118125
[2024-09-19 06:16:32,396][flwr][INFO] - 		round 52: 1.8140651868737263
[2024-09-19 06:16:32,396][flwr][INFO] - 		round 53: 2.012602984905243
[2024-09-19 06:16:32,396][flwr][INFO] - 		round 54: 3.256359207863901
[2024-09-19 06:16:32,396][flwr][INFO] - 		round 55: 2.508888278156519
[2024-09-19 06:16:32,396][flwr][INFO] - 		round 56: 2.1328123677521944
[2024-09-19 06:16:32,396][flwr][INFO] - 		round 57: 1.5023132795240821
[2024-09-19 06:16:32,396][flwr][INFO] - 		round 58: 1.3545151449018908
[2024-09-19 06:16:32,396][flwr][INFO] - 		round 59: 0.8575629256665707
[2024-09-19 06:16:32,396][flwr][INFO] - 		round 60: 2.907290333683051
[2024-09-19 06:16:32,396][flwr][INFO] - 		round 61: 2.316562461853027
[2024-09-19 06:16:32,396][flwr][INFO] - 		round 62: 1.2043820396065712
[2024-09-19 06:16:32,396][flwr][INFO] - 		round 63: 0.8956861933072408
[2024-09-19 06:16:32,396][flwr][INFO] - 		round 64: 0.9546520908673605
[2024-09-19 06:16:32,396][flwr][INFO] - 		round 65: 1.2108935953965827
[2024-09-19 06:16:32,396][flwr][INFO] - 		round 66: 2.025513011476268
[2024-09-19 06:16:32,396][flwr][INFO] - 		round 67: 1.9000441065201392
[2024-09-19 06:16:32,396][flwr][INFO] - 		round 68: 0.7366294503211975
[2024-09-19 06:16:32,396][flwr][INFO] - 		round 69: 1.1010773522513253
[2024-09-19 06:16:32,397][flwr][INFO] - 		round 70: 2.9277465018359097
[2024-09-19 06:16:32,397][flwr][INFO] - 		round 71: 3.3190239201421323
[2024-09-19 06:16:32,397][flwr][INFO] - 		round 72: 1.9330547451972961
[2024-09-19 06:16:32,397][flwr][INFO] - 		round 73: 1.3961076499559941
[2024-09-19 06:16:32,397][flwr][INFO] - 		round 74: 1.848650574684143
[2024-09-19 06:16:32,397][flwr][INFO] - 		round 75: 2.7856482416391373
[2024-09-19 06:16:32,397][flwr][INFO] - 		round 76: 1.4688061567453237
[2024-09-19 06:16:32,397][flwr][INFO] - 		round 77: 3.348412052673452
[2024-09-19 06:16:32,397][flwr][INFO] - 		round 78: 1.2503983041514521
[2024-09-19 06:16:32,397][flwr][INFO] - 		round 79: 1.5057691248172584
[2024-09-19 06:16:32,397][flwr][INFO] - 		round 80: 2.7702298845563615
[2024-09-19 06:16:32,397][flwr][INFO] - 		round 81: 1.275665561358134
[2024-09-19 06:16:32,397][flwr][INFO] - 		round 82: 0.7942148722135104
[2024-09-19 06:16:32,397][flwr][INFO] - 		round 83: 1.4107928276062012
[2024-09-19 06:16:32,397][flwr][INFO] - 		round 84: 1.5550500601530075
[2024-09-19 06:16:32,397][flwr][INFO] - 		round 85: 2.161540372805162
[2024-09-19 06:16:32,397][flwr][INFO] - 		round 86: 1.3973211646080017
[2024-09-19 06:16:32,397][flwr][INFO] - 		round 87: 2.4047136087166634
[2024-09-19 06:16:32,397][flwr][INFO] - 		round 88: 1.589331878857179
[2024-09-19 06:16:32,397][flwr][INFO] - 		round 89: 0.8085929751396179
[2024-09-19 06:16:32,397][flwr][INFO] - 		round 90: 1.492438585669906
[2024-09-19 06:16:32,397][flwr][INFO] - 		round 91: 2.7025019178787866
[2024-09-19 06:16:32,398][flwr][INFO] - 		round 92: 1.0768202328404715
[2024-09-19 06:16:32,398][flwr][INFO] - 		round 93: 3.382274727488673
[2024-09-19 06:16:32,398][flwr][INFO] - 		round 94: 0.8984941763262595
[2024-09-19 06:16:32,398][flwr][INFO] - 		round 95: 1.2854080862469144
[2024-09-19 06:16:32,398][flwr][INFO] - 		round 96: 3.3265311888286044
[2024-09-19 06:16:32,398][flwr][INFO] - 		round 97: 3.0716222303885
[2024-09-19 06:16:32,398][flwr][INFO] - 		round 98: 1.6706932317919847
[2024-09-19 06:16:32,398][flwr][INFO] - 		round 99: 5.685103914316962
[2024-09-19 06:16:32,398][flwr][INFO] - 		round 100: 2.7438865900039673
[2024-09-19 06:16:32,398][flwr][INFO] - 	History (loss, centralized):
[2024-09-19 06:16:32,398][flwr][INFO] - 		round 0: 236.95961356163025
[2024-09-19 06:16:32,398][flwr][INFO] - 		round 1: 314.8323600292206
[2024-09-19 06:16:32,398][flwr][INFO] - 		round 2: 275.57846319675446
[2024-09-19 06:16:32,398][flwr][INFO] - 		round 3: 232.24409687519073
[2024-09-19 06:16:32,398][flwr][INFO] - 		round 4: 236.0022075176239
[2024-09-19 06:16:32,398][flwr][INFO] - 		round 5: 223.45547807216644
[2024-09-19 06:16:32,398][flwr][INFO] - 		round 6: 275.6538553237915
[2024-09-19 06:16:32,398][flwr][INFO] - 		round 7: 244.8714678287506
[2024-09-19 06:16:32,398][flwr][INFO] - 		round 8: 358.55996656417847
[2024-09-19 06:16:32,398][flwr][INFO] - 		round 9: 221.96499860286713
[2024-09-19 06:16:32,398][flwr][INFO] - 		round 10: 256.1852707862854
[2024-09-19 06:16:32,399][flwr][INFO] - 		round 11: 241.1495063304901
[2024-09-19 06:16:32,399][flwr][INFO] - 		round 12: 243.75460958480835
[2024-09-19 06:16:32,399][flwr][INFO] - 		round 13: 319.1035921573639
[2024-09-19 06:16:32,399][flwr][INFO] - 		round 14: 370.9240219593048
[2024-09-19 06:16:32,399][flwr][INFO] - 		round 15: 252.99449932575226
[2024-09-19 06:16:32,399][flwr][INFO] - 		round 16: 229.98141658306122
[2024-09-19 06:16:32,399][flwr][INFO] - 		round 17: 207.78885877132416
[2024-09-19 06:16:32,399][flwr][INFO] - 		round 18: 194.9832283258438
[2024-09-19 06:16:32,399][flwr][INFO] - 		round 19: 198.96304595470428
[2024-09-19 06:16:32,399][flwr][INFO] - 		round 20: 349.6879804134369
[2024-09-19 06:16:32,399][flwr][INFO] - 		round 21: 211.71223163604736
[2024-09-19 06:16:32,399][flwr][INFO] - 		round 22: 197.83693420886993
[2024-09-19 06:16:32,399][flwr][INFO] - 		round 23: 220.7082303762436
[2024-09-19 06:16:32,399][flwr][INFO] - 		round 24: 256.0654927492142
[2024-09-19 06:16:32,399][flwr][INFO] - 		round 25: 199.01076793670654
[2024-09-19 06:16:32,399][flwr][INFO] - 		round 26: 203.5955001115799
[2024-09-19 06:16:32,399][flwr][INFO] - 		round 27: 239.97119915485382
[2024-09-19 06:16:32,399][flwr][INFO] - 		round 28: 177.7108371257782
[2024-09-19 06:16:32,399][flwr][INFO] - 		round 29: 221.1934574842453
[2024-09-19 06:16:32,399][flwr][INFO] - 		round 30: 266.36865425109863
[2024-09-19 06:16:32,399][flwr][INFO] - 		round 31: 814.8991141319275
[2024-09-19 06:16:32,399][flwr][INFO] - 		round 32: 223.40188932418823
[2024-09-19 06:16:32,399][flwr][INFO] - 		round 33: 172.379714012146
[2024-09-19 06:16:32,400][flwr][INFO] - 		round 34: 188.85340213775635
[2024-09-19 06:16:32,400][flwr][INFO] - 		round 35: 220.37343037128448
[2024-09-19 06:16:32,400][flwr][INFO] - 		round 36: 204.7879763841629
[2024-09-19 06:16:32,400][flwr][INFO] - 		round 37: 239.3770271539688
[2024-09-19 06:16:32,400][flwr][INFO] - 		round 38: 391.0763895511627
[2024-09-19 06:16:32,400][flwr][INFO] - 		round 39: 191.99643087387085
[2024-09-19 06:16:32,400][flwr][INFO] - 		round 40: 191.66151893138885
[2024-09-19 06:16:32,400][flwr][INFO] - 		round 41: 208.0507106781006
[2024-09-19 06:16:32,400][flwr][INFO] - 		round 42: 184.6286779642105
[2024-09-19 06:16:32,400][flwr][INFO] - 		round 43: 182.78794407844543
[2024-09-19 06:16:32,400][flwr][INFO] - 		round 44: 147.51084768772125
[2024-09-19 06:16:32,400][flwr][INFO] - 		round 45: 224.15455651283264
[2024-09-19 06:16:32,400][flwr][INFO] - 		round 46: 248.86411702632904
[2024-09-19 06:16:32,400][flwr][INFO] - 		round 47: 267.44094955921173
[2024-09-19 06:16:32,400][flwr][INFO] - 		round 48: 145.7940800189972
[2024-09-19 06:16:32,400][flwr][INFO] - 		round 49: 330.93445432186127
[2024-09-19 06:16:32,400][flwr][INFO] - 		round 50: 196.3268893957138
[2024-09-19 06:16:32,400][flwr][INFO] - 		round 51: 323.4802031517029
[2024-09-19 06:16:32,400][flwr][INFO] - 		round 52: 177.502006649971
[2024-09-19 06:16:32,400][flwr][INFO] - 		round 53: 197.32806944847107
[2024-09-19 06:16:32,400][flwr][INFO] - 		round 54: 167.42883849143982
[2024-09-19 06:16:32,401][flwr][INFO] - 		round 55: 167.63740944862366
[2024-09-19 06:16:32,401][flwr][INFO] - 		round 56: 148.92517751455307
[2024-09-19 06:16:32,401][flwr][INFO] - 		round 57: 163.3907800912857
[2024-09-19 06:16:32,401][flwr][INFO] - 		round 58: 186.57170450687408
[2024-09-19 06:16:32,401][flwr][INFO] - 		round 59: 174.60418462753296
[2024-09-19 06:16:32,401][flwr][INFO] - 		round 60: 284.9017996788025
[2024-09-19 06:16:32,401][flwr][INFO] - 		round 61: 173.7874743938446
[2024-09-19 06:16:32,401][flwr][INFO] - 		round 62: 165.44527900218964
[2024-09-19 06:16:32,401][flwr][INFO] - 		round 63: 146.27642852067947
[2024-09-19 06:16:32,401][flwr][INFO] - 		round 64: 178.88250768184662
[2024-09-19 06:16:32,401][flwr][INFO] - 		round 65: 133.34793955087662
[2024-09-19 06:16:32,401][flwr][INFO] - 		round 66: 184.54650449752808
[2024-09-19 06:16:32,401][flwr][INFO] - 		round 67: 197.4779441356659
[2024-09-19 06:16:32,401][flwr][INFO] - 		round 68: 191.18723273277283
[2024-09-19 06:16:32,401][flwr][INFO] - 		round 69: 203.3732384443283
[2024-09-19 06:16:32,401][flwr][INFO] - 		round 70: 166.5615760087967
[2024-09-19 06:16:32,401][flwr][INFO] - 		round 71: 180.57121467590332
[2024-09-19 06:16:32,401][flwr][INFO] - 		round 72: 140.18981957435608
[2024-09-19 06:16:32,401][flwr][INFO] - 		round 73: 177.37013632059097
[2024-09-19 06:16:32,401][flwr][INFO] - 		round 74: 207.1789540052414
[2024-09-19 06:16:32,401][flwr][INFO] - 		round 75: 188.61102485656738
[2024-09-19 06:16:32,402][flwr][INFO] - 		round 76: 164.9422169327736
[2024-09-19 06:16:32,402][flwr][INFO] - 		round 77: 158.2155829668045
[2024-09-19 06:16:32,402][flwr][INFO] - 		round 78: 155.5544172525406
[2024-09-19 06:16:32,402][flwr][INFO] - 		round 79: 172.67417401075363
[2024-09-19 06:16:32,402][flwr][INFO] - 		round 80: 225.7377132177353
[2024-09-19 06:16:32,402][flwr][INFO] - 		round 81: 153.15514361858368
[2024-09-19 06:16:32,402][flwr][INFO] - 		round 82: 186.14743673801422
[2024-09-19 06:16:32,402][flwr][INFO] - 		round 83: 197.93535828590393
[2024-09-19 06:16:32,402][flwr][INFO] - 		round 84: 139.87571793794632
[2024-09-19 06:16:32,402][flwr][INFO] - 		round 85: 267.81910490989685
[2024-09-19 06:16:32,402][flwr][INFO] - 		round 86: 198.19132900238037
[2024-09-19 06:16:32,402][flwr][INFO] - 		round 87: 149.7783686518669
[2024-09-19 06:16:32,402][flwr][INFO] - 		round 88: 160.24197226762772
[2024-09-19 06:16:32,402][flwr][INFO] - 		round 89: 156.7819185256958
[2024-09-19 06:16:32,402][flwr][INFO] - 		round 90: 148.33892804384232
[2024-09-19 06:16:32,402][flwr][INFO] - 		round 91: 161.9329262971878
[2024-09-19 06:16:32,402][flwr][INFO] - 		round 92: 131.0054919719696
[2024-09-19 06:16:32,402][flwr][INFO] - 		round 93: 222.83596110343933
[2024-09-19 06:16:32,402][flwr][INFO] - 		round 94: 153.0809336900711
[2024-09-19 06:16:32,402][flwr][INFO] - 		round 95: 151.32084584236145
[2024-09-19 06:16:32,402][flwr][INFO] - 		round 96: 189.7887372970581
[2024-09-19 06:16:32,403][flwr][INFO] - 		round 97: 220.39284706115723
[2024-09-19 06:16:32,403][flwr][INFO] - 		round 98: 191.77582186460495
[2024-09-19 06:16:32,403][flwr][INFO] - 		round 99: 261.2749480009079
[2024-09-19 06:16:32,403][flwr][INFO] - 		round 100: 164.25777125358582
[2024-09-19 06:16:32,403][flwr][INFO] - 	History (metrics, distributed, evaluate):
[2024-09-19 06:16:32,403][flwr][INFO] - 	{'accuracy': [(1, 0.17391304347826086),
[2024-09-19 06:16:32,403][flwr][INFO] - 	              (2, 0.14285714285714285),
[2024-09-19 06:16:32,403][flwr][INFO] - 	              (3, 0.12280701754385964),
[2024-09-19 06:16:32,403][flwr][INFO] - 	              (4, 0.42857142857142855),
[2024-09-19 06:16:32,403][flwr][INFO] - 	              (5, 0.5196850393700787),
[2024-09-19 06:16:32,403][flwr][INFO] - 	              (6, 0.03125),
[2024-09-19 06:16:32,403][flwr][INFO] - 	              (7, 0.0),
[2024-09-19 06:16:32,403][flwr][INFO] - 	              (8, 0.09302325581395349),
[2024-09-19 06:16:32,403][flwr][INFO] - 	              (9, 0.0),
[2024-09-19 06:16:32,403][flwr][INFO] - 	              (10, 0.0),
[2024-09-19 06:16:32,403][flwr][INFO] - 	              (11, 0.8823529411764706),
[2024-09-19 06:16:32,403][flwr][INFO] - 	              (12, 0.10294117647058823),
[2024-09-19 06:16:32,403][flwr][INFO] - 	              (13, 0.8125),
[2024-09-19 06:16:32,403][flwr][INFO] - 	              (14, 0.0),
[2024-09-19 06:16:32,403][flwr][INFO] - 	              (15, 0.15384615384615385),
[2024-09-19 06:16:32,403][flwr][INFO] - 	              (16, 0.024096385542168676),
[2024-09-19 06:16:32,403][flwr][INFO] - 	              (17, 0.0),
[2024-09-19 06:16:32,404][flwr][INFO] - 	              (18, 0.425),
[2024-09-19 06:16:32,404][flwr][INFO] - 	              (19, 0.43478260869565216),
[2024-09-19 06:16:32,404][flwr][INFO] - 	              (20, 0.2),
[2024-09-19 06:16:32,404][flwr][INFO] - 	              (21, 0.06521739130434782),
[2024-09-19 06:16:32,404][flwr][INFO] - 	              (22, 0.4),
[2024-09-19 06:16:32,404][flwr][INFO] - 	              (23, 0.30337078651685395),
[2024-09-19 06:16:32,404][flwr][INFO] - 	              (24, 0.6666666666666666),
[2024-09-19 06:16:32,404][flwr][INFO] - 	              (25, 0.037037037037037035),
[2024-09-19 06:16:32,404][flwr][INFO] - 	              (26, 0.4117647058823529),
[2024-09-19 06:16:32,404][flwr][INFO] - 	              (27, 0.13157894736842105),
[2024-09-19 06:16:32,404][flwr][INFO] - 	              (28, 0.0),
[2024-09-19 06:16:32,404][flwr][INFO] - 	              (29, 0.2),
[2024-09-19 06:16:32,404][flwr][INFO] - 	              (30, 0.045454545454545456),
[2024-09-19 06:16:32,404][flwr][INFO] - 	              (31, 0.01282051282051282),
[2024-09-19 06:16:32,404][flwr][INFO] - 	              (32, 0.0),
[2024-09-19 06:16:32,404][flwr][INFO] - 	              (33, 0.4603174603174603),
[2024-09-19 06:16:32,404][flwr][INFO] - 	              (34, 0.2857142857142857),
[2024-09-19 06:16:32,404][flwr][INFO] - 	              (35, 0.0),
[2024-09-19 06:16:32,404][flwr][INFO] - 	              (36, 0.16981132075471697),
[2024-09-19 06:16:32,404][flwr][INFO] - 	              (37, 0.7407407407407407),
[2024-09-19 06:16:32,404][flwr][INFO] - 	              (38, 0.2692307692307692),
[2024-09-19 06:16:32,404][flwr][INFO] - 	              (39, 0.05084745762711865),
[2024-09-19 06:16:32,405][flwr][INFO] - 	              (40, 0.25),
[2024-09-19 06:16:32,405][flwr][INFO] - 	              (41, 0.2916666666666667),
[2024-09-19 06:16:32,405][flwr][INFO] - 	              (42, 0.0),
[2024-09-19 06:16:32,405][flwr][INFO] - 	              (43, 0.08823529411764706),
[2024-09-19 06:16:32,405][flwr][INFO] - 	              (44, 0.5909090909090909),
[2024-09-19 06:16:32,405][flwr][INFO] - 	              (45, 0.0),
[2024-09-19 06:16:32,405][flwr][INFO] - 	              (46, 0.24),
[2024-09-19 06:16:32,405][flwr][INFO] - 	              (47, 0.4444444444444444),
[2024-09-19 06:16:32,405][flwr][INFO] - 	              (48, 0.5909090909090909),
[2024-09-19 06:16:32,405][flwr][INFO] - 	              (49, 0.14285714285714285),
[2024-09-19 06:16:32,405][flwr][INFO] - 	              (50, 0.34328358208955223),
[2024-09-19 06:16:32,405][flwr][INFO] - 	              (51, 0.40789473684210525),
[2024-09-19 06:16:32,405][flwr][INFO] - 	              (52, 0.34782608695652173),
[2024-09-19 06:16:32,405][flwr][INFO] - 	              (53, 0.1346153846153846),
[2024-09-19 06:16:32,405][flwr][INFO] - 	              (54, 0.2222222222222222),
[2024-09-19 06:16:32,405][flwr][INFO] - 	              (55, 0.25),
[2024-09-19 06:16:32,405][flwr][INFO] - 	              (56, 0.65625),
[2024-09-19 06:16:32,405][flwr][INFO] - 	              (57, 0.17073170731707318),
[2024-09-19 06:16:32,405][flwr][INFO] - 	              (58, 0.5483870967741935),
[2024-09-19 06:16:32,405][flwr][INFO] - 	              (59, 0.75),
[2024-09-19 06:16:32,405][flwr][INFO] - 	              (60, 0.019417475728155338),
[2024-09-19 06:16:32,405][flwr][INFO] - 	              (61, 0.13333333333333333),
[2024-09-19 06:16:32,406][flwr][INFO] - 	              (62, 0.6041666666666667),
[2024-09-19 06:16:32,406][flwr][INFO] - 	              (63, 0.8666666666666667),
[2024-09-19 06:16:32,406][flwr][INFO] - 	              (64, 0.7666666666666667),
[2024-09-19 06:16:32,406][flwr][INFO] - 	              (65, 0.417910447761194),
[2024-09-19 06:16:32,406][flwr][INFO] - 	              (66, 0.391304347826087),
[2024-09-19 06:16:32,406][flwr][INFO] - 	              (67, 0.5),
[2024-09-19 06:16:32,406][flwr][INFO] - 	              (68, 0.8),
[2024-09-19 06:16:32,406][flwr][INFO] - 	              (69, 0.2857142857142857),
[2024-09-19 06:16:32,406][flwr][INFO] - 	              (70, 0.06818181818181818),
[2024-09-19 06:16:32,406][flwr][INFO] - 	              (71, 0.21739130434782608),
[2024-09-19 06:16:32,406][flwr][INFO] - 	              (72, 0.0),
[2024-09-19 06:16:32,406][flwr][INFO] - 	              (73, 0.5),
[2024-09-19 06:16:32,406][flwr][INFO] - 	              (74, 0.3333333333333333),
[2024-09-19 06:16:32,406][flwr][INFO] - 	              (75, 0.28125),
[2024-09-19 06:16:32,406][flwr][INFO] - 	              (76, 0.6923076923076923),
[2024-09-19 06:16:32,406][flwr][INFO] - 	              (77, 0.27941176470588236),
[2024-09-19 06:16:32,406][flwr][INFO] - 	              (78, 0.5),
[2024-09-19 06:16:32,406][flwr][INFO] - 	              (79, 0.7407407407407407),
[2024-09-19 06:16:32,406][flwr][INFO] - 	              (80, 0.2857142857142857),
[2024-09-19 06:16:32,406][flwr][INFO] - 	              (81, 0.5),
[2024-09-19 06:16:32,406][flwr][INFO] - 	              (82, 0.7692307692307693),
[2024-09-19 06:16:32,407][flwr][INFO] - 	              (83, 0.6296296296296297),
[2024-09-19 06:16:32,407][flwr][INFO] - 	              (84, 0.4375),
[2024-09-19 06:16:32,407][flwr][INFO] - 	              (85, 0.0),
[2024-09-19 06:16:32,407][flwr][INFO] - 	              (86, 0.2857142857142857),
[2024-09-19 06:16:32,407][flwr][INFO] - 	              (87, 0.5614035087719298),
[2024-09-19 06:16:32,407][flwr][INFO] - 	              (88, 0.25),
[2024-09-19 06:16:32,407][flwr][INFO] - 	              (89, 0.8),
[2024-09-19 06:16:32,407][flwr][INFO] - 	              (90, 0.6296296296296297),
[2024-09-19 06:16:32,407][flwr][INFO] - 	              (91, 0.0),
[2024-09-19 06:16:32,407][flwr][INFO] - 	              (92, 0.5697674418604651),
[2024-09-19 06:16:32,407][flwr][INFO] - 	              (93, 0.023255813953488372),
[2024-09-19 06:16:32,407][flwr][INFO] - 	              (94, 0.6344086021505376),
[2024-09-19 06:16:32,407][flwr][INFO] - 	              (95, 0.6666666666666666),
[2024-09-19 06:16:32,407][flwr][INFO] - 	              (96, 0.3701298701298702),
[2024-09-19 06:16:32,407][flwr][INFO] - 	              (97, 0.09259259259259259),
[2024-09-19 06:16:32,407][flwr][INFO] - 	              (98, 0.3902439024390244),
[2024-09-19 06:16:32,407][flwr][INFO] - 	              (99, 0.08496732026143791),
[2024-09-19 06:16:32,407][flwr][INFO] - 	              (100, 0.391304347826087)]}
[2024-09-19 06:16:32,407][flwr][INFO] - 	History (metrics, centralized):
[2024-09-19 06:16:32,407][flwr][INFO] - 	{'accuracy': [(0, 0.07483192049108447),
[2024-09-19 06:16:32,407][flwr][INFO] - 	              (1, 0.1824028061970184),
[2024-09-19 06:16:32,407][flwr][INFO] - 	              (2, 0.1824028061970184),
[2024-09-19 06:16:32,407][flwr][INFO] - 	              (3, 0.0710318620286466),
[2024-09-19 06:16:32,408][flwr][INFO] - 	              (4, 0.09090909090909091),
[2024-09-19 06:16:32,408][flwr][INFO] - 	              (5, 0.16924875767319497),
[2024-09-19 06:16:32,408][flwr][INFO] - 	              (6, 0.1373867290266004),
[2024-09-19 06:16:32,408][flwr][INFO] - 	              (7, 0.19467991815258695),
[2024-09-19 06:16:32,408][flwr][INFO] - 	              (8, 0.1824028061970184),
[2024-09-19 06:16:32,408][flwr][INFO] - 	              (9, 0.1373867290266004),
[2024-09-19 06:16:32,408][flwr][INFO] - 	              (10, 0.16924875767319497),
[2024-09-19 06:16:32,408][flwr][INFO] - 	              (11, 0.16924875767319497),
[2024-09-19 06:16:32,408][flwr][INFO] - 	              (12, 0.1824028061970184),
[2024-09-19 06:16:32,408][flwr][INFO] - 	              (13, 0.19467991815258695),
[2024-09-19 06:16:32,408][flwr][INFO] - 	              (14, 0.19731072785735165),
[2024-09-19 06:16:32,408][flwr][INFO] - 	              (15, 0.29494299912306343),
[2024-09-19 06:16:32,408][flwr][INFO] - 	              (16, 0.10757088570593394),
[2024-09-19 06:16:32,408][flwr][INFO] - 	              (17, 0.21631102016954107),
[2024-09-19 06:16:32,408][flwr][INFO] - 	              (18, 0.31511254019292606),
[2024-09-19 06:16:32,408][flwr][INFO] - 	              (19, 0.26132709733995907),
[2024-09-19 06:16:32,408][flwr][INFO] - 	              (20, 0.4016369482607425),
[2024-09-19 06:16:32,408][flwr][INFO] - 	              (21, 0.21280327389652148),
[2024-09-19 06:16:32,408][flwr][INFO] - 	              (22, 0.31920491084478225),
[2024-09-19 06:16:32,408][flwr][INFO] - 	              (23, 0.3045893013738673),
[2024-09-19 06:16:32,408][flwr][INFO] - 	              (24, 0.3051739257527039),
[2024-09-19 06:16:32,408][flwr][INFO] - 	              (25, 0.3291435252850044),
[2024-09-19 06:16:32,408][flwr][INFO] - 	              (26, 0.20140309850920785),
[2024-09-19 06:16:32,408][flwr][INFO] - 	              (27, 0.2572347266881029),
[2024-09-19 06:16:32,409][flwr][INFO] - 	              (28, 0.35603624671148787),
[2024-09-19 06:16:32,409][flwr][INFO] - 	              (29, 0.28734288219818765),
[2024-09-19 06:16:32,409][flwr][INFO] - 	              (30, 0.23531131248173048),
[2024-09-19 06:16:32,409][flwr][INFO] - 	              (31, 0.19467991815258695),
[2024-09-19 06:16:32,409][flwr][INFO] - 	              (32, 0.29318912598655367),
[2024-09-19 06:16:32,409][flwr][INFO] - 	              (33, 0.256357790119848),
[2024-09-19 06:16:32,409][flwr][INFO] - 	              (34, 0.33177433498976905),
[2024-09-19 06:16:32,409][flwr][INFO] - 	              (35, 0.22128032738965214),
[2024-09-19 06:16:32,409][flwr][INFO] - 	              (36, 0.34200526161940953),
[2024-09-19 06:16:32,409][flwr][INFO] - 	              (37, 0.3744519146448407),
[2024-09-19 06:16:32,409][flwr][INFO] - 	              (38, 0.26571178018123354),
[2024-09-19 06:16:32,409][flwr][INFO] - 	              (39, 0.1335866705641625),
[2024-09-19 06:16:32,409][flwr][INFO] - 	              (40, 0.3770827243496054),
[2024-09-19 06:16:32,409][flwr][INFO] - 	              (41, 0.3975445776088863),
[2024-09-19 06:16:32,409][flwr][INFO] - 	              (42, 0.29114294066062557),
[2024-09-19 06:16:32,409][flwr][INFO] - 	              (43, 0.38409821689564455),
[2024-09-19 06:16:32,409][flwr][INFO] - 	              (44, 0.4671148786904414),
[2024-09-19 06:16:32,409][flwr][INFO] - 	              (45, 0.29026600409237063),
[2024-09-19 06:16:32,409][flwr][INFO] - 	              (46, 0.24904998538439052),
[2024-09-19 06:16:32,409][flwr][INFO] - 	              (47, 0.36100555393159894),
[2024-09-19 06:16:32,409][flwr][INFO] - 	              (48, 0.47939199064600996),
[2024-09-19 06:16:32,409][flwr][INFO] - 	              (49, 0.30985092078339666),
[2024-09-19 06:16:32,409][flwr][INFO] - 	              (50, 0.33177433498976905),
[2024-09-19 06:16:32,410][flwr][INFO] - 	              (51, 0.2136802104647764),
[2024-09-19 06:16:32,410][flwr][INFO] - 	              (52, 0.24232680502776965),
[2024-09-19 06:16:32,410][flwr][INFO] - 	              (53, 0.27038877521192634),
[2024-09-19 06:16:32,410][flwr][INFO] - 	              (54, 0.40660625548085355),
[2024-09-19 06:16:32,410][flwr][INFO] - 	              (55, 0.397252265419468),
[2024-09-19 06:16:32,410][flwr][INFO] - 	              (56, 0.4837766734872844),
[2024-09-19 06:16:32,410][flwr][INFO] - 	              (57, 0.3572054954691611),
[2024-09-19 06:16:32,410][flwr][INFO] - 	              (58, 0.36451330020461853),
[2024-09-19 06:16:32,410][flwr][INFO] - 	              (59, 0.30575855013154046),
[2024-09-19 06:16:32,410][flwr][INFO] - 	              (60, 0.3490207541654487),
[2024-09-19 06:16:32,410][flwr][INFO] - 	              (61, 0.27360420929552765),
[2024-09-19 06:16:32,410][flwr][INFO] - 	              (62, 0.38760596316866414),
[2024-09-19 06:16:32,410][flwr][INFO] - 	              (63, 0.4381759719380298),
[2024-09-19 06:16:32,410][flwr][INFO] - 	              (64, 0.36217480268927216),
[2024-09-19 06:16:32,410][flwr][INFO] - 	              (65, 0.5346389944460684),
[2024-09-19 06:16:32,410][flwr][INFO] - 	              (66, 0.39228295819935693),
[2024-09-19 06:16:32,410][flwr][INFO] - 	              (67, 0.33966676410406316),
[2024-09-19 06:16:32,410][flwr][INFO] - 	              (68, 0.4405144694533762),
[2024-09-19 06:16:32,410][flwr][INFO] - 	              (69, 0.35691318327974275),
[2024-09-19 06:16:32,410][flwr][INFO] - 	              (70, 0.4329143525285004),
[2024-09-19 06:16:32,410][flwr][INFO] - 	              (71, 0.4609763227126571),
[2024-09-19 06:16:32,411][flwr][INFO] - 	              (72, 0.45103770827243495),
[2024-09-19 06:16:32,411][flwr][INFO] - 	              (73, 0.4410990938322128),
[2024-09-19 06:16:32,411][flwr][INFO] - 	              (74, 0.3680210464776381),
[2024-09-19 06:16:32,411][flwr][INFO] - 	              (75, 0.4513300204618533),
[2024-09-19 06:16:32,411][flwr][INFO] - 	              (76, 0.42356036246711487),
[2024-09-19 06:16:32,411][flwr][INFO] - 	              (77, 0.41332943583747445),
[2024-09-19 06:16:32,411][flwr][INFO] - 	              (78, 0.42356036246711487),
[2024-09-19 06:16:32,411][flwr][INFO] - 	              (79, 0.5399006138555977),
[2024-09-19 06:16:32,411][flwr][INFO] - 	              (80, 0.388482899736919),
[2024-09-19 06:16:32,411][flwr][INFO] - 	              (81, 0.413914060216311),
[2024-09-19 06:16:32,411][flwr][INFO] - 	              (82, 0.36363636363636365),
[2024-09-19 06:16:32,411][flwr][INFO] - 	              (83, 0.2809120140309851),
[2024-09-19 06:16:32,411][flwr][INFO] - 	              (84, 0.5095001461560947),
[2024-09-19 06:16:32,411][flwr][INFO] - 	              (85, 0.36275942706810876),
[2024-09-19 06:16:32,411][flwr][INFO] - 	              (86, 0.31189710610932475),
[2024-09-19 06:16:32,411][flwr][INFO] - 	              (87, 0.4586378251973107),
[2024-09-19 06:16:32,411][flwr][INFO] - 	              (88, 0.45629932768196435),
[2024-09-19 06:16:32,411][flwr][INFO] - 	              (89, 0.4595147617655656),
[2024-09-19 06:16:32,411][flwr][INFO] - 	              (90, 0.4934229757380883),
[2024-09-19 06:16:32,411][flwr][INFO] - 	              (91, 0.4165448699210757),
[2024-09-19 06:16:32,411][flwr][INFO] - 	              (92, 0.5080385852090032),
[2024-09-19 06:16:32,411][flwr][INFO] - 	              (93, 0.33908213972522655),
[2024-09-19 06:16:32,411][flwr][INFO] - 	              (94, 0.43934522069570303),
[2024-09-19 06:16:32,412][flwr][INFO] - 	              (95, 0.5074539608301666),
[2024-09-19 06:16:32,412][flwr][INFO] - 	              (96, 0.4007600116924876),
[2024-09-19 06:16:32,412][flwr][INFO] - 	              (97, 0.3256357790119848),
[2024-09-19 06:16:32,412][flwr][INFO] - 	              (98, 0.3040046769950307),
[2024-09-19 06:16:32,412][flwr][INFO] - 	              (99, 0.21806489330605086),
[2024-09-19 06:16:32,412][flwr][INFO] - 	              (100, 0.42297573808827826)]}
[2024-09-19 06:16:32,412][flwr][INFO] - 
